version: "3.9"
services:
  api-1:
    image: zcusdev02acr.azurecr.io/bizworks/api-ref:1.0.0
    ports:
      - "8500:5000"   # not required though
  ui-1:
    image: zcusdev02acr.azurecr.io/bizworks/ui-ref:1.0.0
    ports:
      - "8501:80"    # not required though
    depends_on:
      - api
  apigee:
    build: .
    ports:
      - "8080:8080" 
      - "80:8998"
    depends_on:
      - api-1
      - ui-1